// =============================================================================
// 参数组：日志与高级覆写 — 日志去向与格式、张量校验、离线、元数据/张量类型覆写、内置工具
//   本文件是这些参数的唯一声明处：命令行、校验、UI、默认值、v1 迁移都由它推导
//   只有 verbose 与 log_disable 在 v1 里存在，其余参数旧配置没有对应字段，一律 inherit
// =============================================================================

import type { ParamDef } from '../schema';
import type { ConfigKey } from '../../types';

export const PARAMS_ADVANCED = [
  {
    key: 'advanced.verbose',
    flag: '--verbose',
    short: '-v',
    type: 'bool',
    tier: 1,
    group: 'advanced',
    label: '输出全部日志',
    desc: '把日志级别拉到无限大，每条内部消息都会打印，只在排查崩溃或行为异常时开；开着时日志量极大，也会拖慢生成',
    legacy: { path: 'optional.verbose', emits: (v) => v === true },
  },
  {
    key: 'advanced.log_disable',
    flag: '--log-disable',
    type: 'bool',
    tier: 1,
    group: 'advanced',
    label: '关闭全部日志',
    desc: '完全不输出日志，和「输出全部日志」相反：本启动器的日志面板与日志文件都会变空，出问题时也就无从回溯，只在刷屏干扰时短暂使用',
    legacy: { path: 'optional.log_disable', emits: (v) => v === true },
  },
  {
    key: 'advanced.log_file',
    flag: '--log-file',
    type: 'path',
    envName: 'LLAMA_ARG_LOG_FILE',
    tier: 2,
    group: 'advanced',
    label: '日志文件',
    desc: '把日志另外写进指定文件，进程退出或界面滚走之后仍能回看；目录不存在或文件被占用会导致启动失败',
  },
  {
    key: 'advanced.log_verbosity',
    flag: '--log-verbosity',
    short: '-lv',
    type: 'int',
    llamaDefault: 3,
    envName: 'LLAMA_ARG_LOG_VERBOSITY',
    tier: 2,
    group: 'advanced',
    label: '日志级别',
    desc: '高于该级别的日志被丢弃：0 通用、1 错误、2 警告、3 信息、4 trace、5 debug；只改变打印量，不改变服务行为',
    min: 0,
    max: 5,
  },
  {
    key: 'advanced.log_prefix',
    flag: '--log-prefix',
    negFlag: '--no-log-prefix',
    type: 'bool',
    envName: 'LLAMA_ARG_LOG_PREFIX',
    tier: 2,
    group: 'advanced',
    label: '日志前缀',
    desc: '每行前面带上来源模块前缀，多后端混跑时用来分辨是谁打的日志；关掉只是省掉一串字符，可读性会下降',
  },
  {
    key: 'advanced.log_timestamps',
    flag: '--log-timestamps',
    negFlag: '--no-log-timestamps',
    type: 'bool',
    envName: 'LLAMA_ARG_LOG_TIMESTAMPS',
    tier: 2,
    group: 'advanced',
    label: '日志时间戳',
    desc: '每行前加时间戳，用来量各阶段耗时和并发时序；不需要定位「卡在哪一秒」时可以关',
  },
  {
    key: 'advanced.log_jsonl',
    flag: '--log-jsonl',
    negFlag: '--no-log-jsonl',
    type: 'bool',
    llamaDefault: 'disabled',
    envName: 'LLAMA_ARG_LOG_JSONL',
    tier: 2,
    group: 'advanced',
    label: 'JSONL 日志',
    desc: '每行输出一个 JSON 对象到 stdout，便于让程序解析或采集；它同时会关掉彩色日志，人读起来的负担比默认格式重',
  },
  {
    key: 'advanced.log_colors',
    flag: '--log-colors',
    type: 'enum',
    llamaDefault: "'auto'",
    envName: 'LLAMA_ARG_LOG_COLORS',
    tier: 2,
    group: 'advanced',
    label: '彩色日志',
    desc: 'on 强制上色、off 完全不涂色、auto 只在输出到终端时上色；日志被存成文件或喂给解析器时选 off，避免 ANSI 转义码混进文本',
    options: ['on', 'off', 'auto'],
  },
  {
    key: 'advanced.check_tensors',
    flag: '--check-tensors',
    type: 'bool',
    llamaDefault: false,
    tier: 2,
    group: 'advanced',
    label: '校验张量数据',
    desc: '加载时逐个检查权重有没有 NaN/Inf 等非法值，用来确认下载或量化出来的 GGUF 是否损坏；大模型上会明显拉长加载时间',
  },
  {
    key: 'advanced.offline',
    flag: '--offline',
    type: 'bool',
    envName: 'LLAMA_ARG_OFFLINE',
    tier: 2,
    group: 'advanced',
    label: '离线模式',
    desc: '强制走本地缓存并禁止任何网络访问，用于隔离环境或确认不会偷偷下载；开着时所有联网下载模型/投影器的功能都会失败',
  },
  {
    key: 'advanced.escape',
    flag: '--escape',
    short: '-e',
    negFlag: '--no-escape',
    type: 'bool',
    llamaDefault: true,
    tier: 2,
    group: 'advanced',
    label: '处理转义序列',
    desc: '把参数里的 \\n \\t \\" 等转成真实字符，模板与 system prompt 需要换行时依赖它；路径或正则里反斜杠被吃掉时才关掉',
  },
  {
    key: 'advanced.override_kv',
    flag: '--override-kv',
    emit: 'repeat',
    type: 'string[]',
    tier: 2,
    group: 'advanced',
    label: '覆写模型元数据',
    desc: '每条形如 KEY=TYPE:VALUE（TYPE 限 int/float/bool/str），例如 tokenizer.ggml.add_bos_token=bool:false，用来修正元数据写坏的模型；键名写错不会报错只是不生效，改错模板相关键会让输出直接乱掉',
  },
  {
    key: 'advanced.override_tensor',
    flag: '--override-tensor',
    short: '-ot',
    emit: 'repeat',
    type: 'string[]',
    envName: 'LLAMA_ARG_OVERRIDE_TENSOR',
    tier: 2,
    group: 'advanced',
    label: '覆写张量存放位置',
    desc: '每条形如 <张量名模式>=<buffer 类型>，例如 ffn_up=CPU，手工把指定层留在内存或压进显存，比 --tensor-split 更细粒度；模式匹配过宽会退化成 CPU 计算，生成速度大幅下降',
  },
  {
    key: 'advanced.tools',
    flag: '--tools',
    emit: 'csv',
    type: 'string[]',
    llamaDefault: 'no tools',
    envName: 'LLAMA_ARG_TOOLS',
    tier: 2,
    group: 'advanced',
    label: '内置工具',
    desc: '实验特性：填 all 或具体工具名（逗号分隔传给 llama-server）。开放后模型可以借 read_file / write_file / edit_file / exec_shell_command / grep_search 等内置工具在你机器上执行命令和读写文件，只在可信局域网开启；一旦启用，llama-server 还会默认把 --cors-origins 收紧到 localhost',
    options: ['all', 'read_file', 'file_glob_search', 'grep_search', 'exec_shell_command', 'write_file', 'edit_file', 'get_info'],
  },
] as const satisfies readonly ParamDef<ConfigKey>[];
