// =============================================================================
// 参数组：计算与线程 — CPU 线程/亲和性/NUMA、MoE 与稠密 FFN 权重驻留、内核开关
//   本文件是这些参数的唯一声明处：命令行、校验、UI、默认值、v1 迁移都由它推导
// =============================================================================

import type { ParamDef } from '../schema';
import type { ConfigKey } from '../../types';

export const PARAMS_COMPUTE = [
  {
    key: 'compute.threads',
    flag: '--threads',
    short: '-t',
    type: 'int',
    llamaDefault: -1,
    envName: 'LLAMA_ARG_THREADS',
    tier: 0,
    group: 'compute',
    label: '生成线程数',
    desc: '逐 token 生成阶段用的 CPU 线程数，-1 跟随自动探测；与其它程序抢 CPU 时手动减小',
    min: -1,
    legacy: { path: 'threads' },
  },
  {
    key: 'compute.threads_batch',
    flag: '--threads-batch',
    short: '-tb',
    type: 'int',
    llamaDefault: 'same as --threads',
    tier: 1,
    group: 'compute',
    label: '批处理线程数',
    desc: 'prompt 预填充阶段的线程数，通常可以比生成线程更激进；保持 inherit 即跟随 --threads',
    min: -1,
    legacy: { path: 'threads_batch', emits: (v) => Number(v) > 0 },
  },
  {
    key: 'compute.threads_http',
    flag: '--threads-http',
    type: 'int',
    llamaDefault: -1,
    envName: 'LLAMA_ARG_THREADS_HTTP',
    tier: 2,
    group: 'compute',
    label: 'HTTP 线程数',
    desc: '处理 HTTP 请求的线程数，只有高并发且 CPU 被打满时才需要指定',
    min: -1,
  },
  {
    key: 'compute.numa',
    flag: '--numa',
    type: 'enum',
    envName: 'LLAMA_ARG_NUMA',
    tier: 1,
    group: 'compute',
    label: 'NUMA 优化',
    desc: '双路/多 NUMA 机型上减少跨节点访存；改过这项后建议先释放系统 page cache 再启动',
    options: ['distribute', 'isolate', 'numactl'],
    legacy: { path: 'optional.numa', emits: (v) => Boolean(v) && v !== 'none' },
  },
  {
    key: 'compute.cpu_mask',
    flag: '--cpu-mask',
    short: '-C',
    type: 'string',
    llamaDefault: '""',
    tier: 1,
    group: 'compute',
    label: 'CPU 亲和掩码',
    desc: '任意长度的十六进制位掩码，与 --cpu-range 互补使用；Windows 上通常不生效',
  },
  {
    key: 'compute.cpu_range',
    flag: '--cpu-range',
    short: '-Cr',
    type: 'string',
    tier: 1,
    group: 'compute',
    label: 'CPU 亲和区间',
    desc: '形如 0-7 的 CPU 编号区间，用来把推理固定在物理核或某个 NUMA 节点上',
  },
  {
    key: 'compute.cpu_strict',
    flag: '--cpu-strict',
    type: 'int',
    llamaDefault: 0,
    tier: 2,
    group: 'compute',
    label: '严格 CPU 绑定',
    desc: '2 会把线程硬钉在指定核上，吞吐略升但可能饿死同机其它进程',
    min: 0,
    max: 2,
  },
  {
    key: 'compute.prio',
    flag: '--prio',
    type: 'int',
    llamaDefault: 0,
    tier: 1,
    group: 'compute',
    label: '进程优先级',
    desc: 'low(-1) 到 realtime(3)；realtime 会拖慢系统响应，只适合短时独占跑分',
    min: -1,
    max: 3,
  },
  {
    key: 'compute.poll',
    flag: '--poll',
    type: 'int',
    llamaDefault: 50,
    tier: 1,
    group: 'compute',
    label: '轮询等待强度',
    desc: '等待任务时的轮询级别，0 改为纯等待：省 CPU 但首 token 延迟更高',
    min: 0,
  },
  {
    key: 'compute.cpu_moe',
    flag: '--cpu-moe',
    short: '-cmoe',
    type: 'bool',
    envName: 'LLAMA_ARG_CPU_MOE',
    tier: 1,
    group: 'compute',
    label: '专家权重留在 CPU',
    desc: '把所有 MoE 专家权重常驻主存、只把注意力等热路径放显存，是大模型塞进小显存的首选；每 token 更慢',
  },
  {
    key: 'compute.n_cpu_moe',
    flag: '--n-cpu-moe',
    short: '-ncmoe',
    type: 'int',
    envName: 'LLAMA_ARG_N_CPU_MOE',
    tier: 1,
    group: 'compute',
    label: '前 N 层专家留 CPU',
    desc: '只把前 N 层的 MoE 专家权重留在主存，用来在显存占用与速度之间取中间点',
    unit: '层',
    min: 0,
  },
  {
    key: 'compute.n_cpu_ffn',
    flag: '--n-cpu-ffn',
    short: '-ncffn',
    type: 'int',
    envName: 'LLAMA_ARG_N_CPU_FFN',
    tier: 1,
    group: 'compute',
    label: '前 N 层稠密 FFN 留 CPU',
    desc: '稠密模型专用：把前 N 层的 FFN 权重留在主存；MoE 模型请用 n-cpu-moe',
    unit: '层',
    min: 0,
  },
  {
    key: 'compute.repack',
    flag: '--repack',
    negFlag: '--no-repack',
    type: 'bool',
    llamaDefault: 'enabled',
    envName: 'LLAMA_ARG_REPACK',
    tier: 2,
    group: 'compute',
    label: '权重重排',
    desc: '加载时把权重转换成更快的存储布局，代价是加载更慢；怀疑量化 kernel 有问题时可用关掉做对照',
  },
  {
    key: 'compute.op_offload',
    flag: '--op-offload',
    negFlag: '--no-op-offload',
    type: 'bool',
    llamaDefault: true,
    tier: 2,
    group: 'compute',
    label: 'host 算子卸载',
    desc: '把 host 侧张量运算搬到设备上执行，个别后端结果异常或启动失败时这是第一个要关的开关',
  },
  {
    key: 'compute.no_host',
    flag: '--no-host',
    type: 'bool',
    envName: 'LLAMA_ARG_NO_HOST',
    tier: 2,
    group: 'compute',
    label: '绕过 host buffer',
    desc: '跳过 host buffer 以允许使用额外 buffer，显存极度吃紧时才尝试，反而变慢就关掉',
  },
  {
    key: 'compute.perf',
    flag: '--perf',
    negFlag: '--no-perf',
    type: 'bool',
    llamaDefault: false,
    envName: 'LLAMA_ARG_PERF',
    tier: 2,
    group: 'compute',
    label: '内部性能计时',
    desc: '打开 libllama 内部耗时统计，日志量暴增且自身有开销，只在定位性能瓶颈时短期使用',
  },
] as const satisfies readonly ParamDef<ConfigKey>[];
