// =============================================================================
// 参数组：显存与缓存 — 层卸载与多卡切分、KV cache 精度、prompt 缓存、--fit 自适应
//   本文件是这些参数的唯一声明处：命令行、校验、UI、默认值、v1 迁移都由它推导
// =============================================================================

import type { ParamDef } from '../schema';
import type { ConfigKey } from '../../types';

const KV_CACHE_TYPES: readonly string[] = [
  'f32',
  'f16',
  'bf16',
  'q8_0',
  'q4_0',
  'q4_1',
  'iq4_nl',
  'q5_0',
  'q5_1',
];

export const PARAMS_MEMORY = [
  {
    key: 'memory.ngl',
    flag: '--gpu-layers',
    short: '-ngl',
    type: 'string',
    llamaDefault: 'auto',
    envName: 'LLAMA_ARG_N_GPU_LAYERS',
    tier: 0,
    group: 'memory',
    label: '卸载层数',
    desc: 'llama 同时接受数字、auto 与 all：auto 交给 --fit 决定，all 尽量全部塞进显存。OOM 时往下减数字',
    options: ['auto', 'all'],
    legacy: { path: 'ngl' },
  },
  {
    key: 'memory.device',
    flag: '--device',
    short: '-dev',
    type: 'string',
    envName: 'LLAMA_ARG_DEVICE',
    tier: 0,
    group: 'memory',
    label: '计算设备',
    desc: '逗号分隔的设备名，需先用 --list-devices 查表；填 none 表示完全不卸载到 GPU，纯 CPU 跑',
  },
  {
    key: 'memory.split_mode',
    flag: '--split-mode',
    short: '-sm',
    type: 'enum',
    llamaDefault: 'layer',
    envName: 'LLAMA_ARG_SPLIT_MODE',
    tier: 2,
    group: 'memory',
    label: '多卡切分方式',
    desc: 'none 只用一张卡，layer 按层流水线切、跨卡带宽差时更稳，row/tensor 按行并行切',
    options: ['none', 'layer', 'row', 'tensor'],
  },
  {
    key: 'memory.tensor_split',
    flag: '--tensor-split',
    short: '-ts',
    type: 'string',
    envName: 'LLAMA_ARG_TENSOR_SPLIT',
    tier: 2,
    group: 'memory',
    label: '各卡卸载比例',
    desc: '按卡的显存比例写原值，如 3,1；显存差距大的双卡混跑时才需要',
  },
  {
    key: 'memory.main_gpu',
    flag: '--main-gpu',
    short: '-mg',
    type: 'int',
    llamaDefault: 0,
    envName: 'LLAMA_ARG_MAIN_GPU',
    tier: 2,
    group: 'memory',
    label: '主卡编号',
    desc: 'split-mode 为 none 时决定模型放哪张卡，为 row 时决定中间结果与 KV 放哪张卡',
    min: 0,
  },
  {
    key: 'memory.cache_type_k',
    flag: '--cache-type-k',
    short: '-ctk',
    type: 'enum',
    llamaDefault: 'f16',
    envName: 'LLAMA_ARG_CACHE_TYPE_K',
    tier: 0,
    group: 'memory',
    label: 'K 缓存精度',
    desc: 'K 量化到 q8_0 可省下大量显存换更长上下文，代价是长距离检索精度略降；bf16 需设备支持',
    options: KV_CACHE_TYPES,
    legacy: { path: 'cache_type_k' },
  },
  {
    key: 'memory.cache_type_v',
    flag: '--cache-type-v',
    short: '-ctv',
    type: 'enum',
    llamaDefault: 'f16',
    envName: 'LLAMA_ARG_CACHE_TYPE_V',
    tier: 0,
    group: 'memory',
    label: 'V 缓存精度',
    desc: 'V 比 K 对量化更敏感，通常保持比 K 高一档；显存实在不足再降',
    options: KV_CACHE_TYPES,
    legacy: { path: 'cache_type_v' },
  },
  {
    key: 'memory.kv_unified',
    flag: '--kv-unified',
    short: '-kvu',
    negFlag: '--no-kv-unified',
    type: 'bool',
    llamaDefault: 'enabled if number of slots is auto',
    envName: 'LLAMA_ARG_KV_UNIFIED',
    tier: 1,
    group: 'memory',
    label: '统一 KV 池',
    desc: '所有并发槽共用一块 KV buffer，长对话更容易塞进显存；关掉后每槽独立配额，避免互相挤占',
    legacy: { path: 'kv_unified' },
  },
  {
    key: 'memory.kv_unified_per_slot',
    flag: '--kv-unified-per-slot',
    type: 'int',
    llamaDefault: 'unset, behavior unchanged',
    envName: 'LLAMA_ARG_KV_UNIFIED_PER_SLOT',
    tier: 2,
    group: 'memory',
    label: '每槽上下文上限',
    desc: '限制单个并发槽能占的上下文；不填 --ctx-size 时共享 KV 池会按 槽数×N 预留显存',
    unit: 'tokens',
    min: 1,
  },
  {
    key: 'memory.kv_offload',
    flag: '--kv-offload',
    short: '-kvo',
    negFlag: '--no-kv-offload',
    type: 'bool',
    llamaDefault: 'enabled',
    envName: 'LLAMA_ARG_KV_OFFLOAD',
    tier: 1,
    group: 'memory',
    label: 'KV 换出到内存',
    desc: '显存放不下时把 KV 换出到主存以撑住更长上下文，代价是生成速度明显下降',
  },
  {
    key: 'memory.swa_full',
    flag: '--swa-full',
    type: 'bool',
    llamaDefault: false,
    envName: 'LLAMA_ARG_SWA_FULL',
    tier: 2,
    group: 'memory',
    label: '全尺寸 SWA 缓存',
    desc: '给滑动窗口注意力模型保留全尺寸缓存来换更稳的长文质量，显存占用随之上升',
  },
  {
    key: 'memory.cache_ram',
    flag: '--cache-ram',
    short: '-cram',
    type: 'int',
    llamaDefault: '8192, -1 - no limit, 0 - disable',
    envName: 'LLAMA_ARG_CACHE_RAM',
    tier: 1,
    group: 'memory',
    label: '缓存驻留上限',
    desc: '空闲 KV 缓存在主存里最多占多少 MiB，0 关闭、-1 不限；设太小会让多轮对话反复重算 prompt',
    unit: 'MiB',
    min: -1,
  },
  {
    key: 'memory.cache_idle_slots',
    flag: '--cache-idle-slots',
    negFlag: '--no-cache-idle-slots',
    type: 'bool',
    llamaDefault: 'enabled, requires cache-ram',
    envName: 'LLAMA_ARG_CACHE_IDLE_SLOTS',
    tier: 2,
    group: 'memory',
    label: '缓存空闲槽位',
    desc: '接到新任务时把空闲槽的内容存进 prompt 缓存，需 cache-ram 未关闭才有意义',
  },
  {
    key: 'memory.cache_prompt',
    flag: '--cache-prompt',
    negFlag: '--no-cache-prompt',
    type: 'bool',
    llamaDefault: 'enabled',
    envName: 'LLAMA_ARG_CACHE_PROMPT',
    tier: 1,
    group: 'memory',
    label: 'Prompt 缓存',
    desc: '复用已算过的 prompt 前缀，多轮对话省掉重复计算；排查缓存串味时才关',
  },
  {
    key: 'memory.cache_reuse',
    flag: '--cache-reuse',
    type: 'int',
    llamaDefault: 0,
    envName: 'LLAMA_ARG_CACHE_REUSE',
    tier: 1,
    group: 'memory',
    label: 'KV 位移复用阈值',
    desc: '允许通过位移复用的最小片段长度，需 prompt 缓存开启；调大更难命中但更省显存',
    unit: 'tokens',
    min: 0,
  },
  {
    key: 'memory.context_shift',
    flag: '--context-shift',
    negFlag: '--no-context-shift',
    type: 'bool',
    llamaDefault: 'disabled',
    envName: 'LLAMA_ARG_CONTEXT_SHIFT',
    tier: 1,
    group: 'memory',
    label: '上下文滚动',
    desc: '上下文写满后挤掉最早的 token 继续生成，用于无限续写；会静默丢历史，聊天场景慎用',
  },
  {
    key: 'memory.fit',
    flag: '--fit',
    short: '-fit',
    type: 'enum',
    llamaDefault: 'on',
    envName: 'LLAMA_ARG_FIT',
    tier: 0,
    group: 'memory',
    label: '显存自适应',
    desc: '按空闲显存自动调整「没有显式设置」的参数；本启动器把多数参数做成 inherit 正是为了留着它',
    options: ['on', 'off'],
  },
  {
    key: 'memory.fit_target',
    flag: '--fit-target',
    short: '-fitt',
    type: 'int',
    llamaDefault: 1024,
    envName: 'LLAMA_ARG_FIT_TARGET',
    tier: 1,
    group: 'memory',
    label: '自适应显存余量',
    desc: '每张卡为目标预留的显存，跑长上下文仍 OOM 时逐步加大',
    unit: 'MiB',
    min: 0,
    requires: [{ key: 'memory.fit', noneOf: ['off'] }],
  },
  {
    key: 'memory.fit_ctx',
    flag: '--fit-ctx',
    short: '-fitc',
    type: 'int',
    llamaDefault: 4096,
    envName: 'LLAMA_ARG_FIT_CTX',
    tier: 2,
    group: 'memory',
    label: '自适应上下文下限',
    desc: '--fit 收缩上下文时允许的最小值，防止自动缩到不可用的长度',
    unit: 'tokens',
    min: 1,
    requires: [{ key: 'memory.fit', noneOf: ['off'] }],
  },
  {
    key: 'memory.ctx_checkpoints',
    flag: '--ctx-checkpoints',
    short: '-ctxcp',
    type: 'int',
    llamaDefault: 32,
    envName: 'LLAMA_ARG_CTX_CHECKPOINTS',
    tier: 1,
    group: 'memory',
    label: '上下文检查点数',
    desc: '每个槽最多保留多少个可回退的上下文快照，用于编辑早期消息后续写；越多越占内存',
    min: 0,
  },
  {
    key: 'memory.checkpoint_min_step',
    flag: '--checkpoint-min-step',
    short: '-cms',
    type: 'int',
    llamaDefault: '8192, 0 = no minimum',
    envName: 'LLAMA_ARG_CHECKPOINT_MIN_SPACING_NT',
    tier: 2,
    group: 'memory',
    label: '检查点最小间隔',
    desc: '两个上下文检查点之间的最小 token 间隔，调小快照更密、内存开销更大',
    unit: 'tokens',
    min: 0,
  },
] as const satisfies readonly ParamDef<ConfigKey>[];
