// =============================================================================
// 参数组：模型加载 — GGUF 路径、上下文与批规模、RoPE 扩展、对话模板
//   本文件是这些参数的唯一声明处：命令行、校验、UI、默认值、v1 迁移都由它推导
// =============================================================================

import type { ParamDef } from '../schema';
import type { ConfigKey } from '../../types';

const YARN_SCALING: readonly string[] = ['yarn'];

export const PARAMS_MODEL = [
  {
    key: 'model.model',
    flag: '--model',
    short: '-m',
    type: 'path',
    tier: 0,
    group: 'model',
    label: '模型文件',
    desc: '单模型模式启动时加载的 GGUF 路径；用 --models-dir 做路由模式时可以不填',
    legacy: { path: 'optional.model', emits: (v) => Boolean(v) },
  },
  {
    key: 'model.ctx_size',
    flag: '--ctx-size',
    short: '-c',
    type: 'int',
    llamaDefault: '0, 0 = loaded from model',
    envName: 'LLAMA_ARG_CTX_SIZE',
    tier: 0,
    group: 'model',
    label: '上下文长度',
    desc: '显式设置会占住等比例的 KV 显存，并让 --fit 不再调整它；不确定时保持 inherit',
    unit: 'tokens',
    min: 1,
    legacy: { path: 'ctx_size' },
  },
  {
    key: 'model.batch_size',
    flag: '--batch-size',
    short: '-b',
    type: 'int',
    llamaDefault: 2048,
    envName: 'LLAMA_ARG_BATCH',
    tier: 0,
    group: 'model',
    label: '逻辑批大小',
    desc: '一次 prompt 处理送入的最大 token 数，调大提高吞吐、抬高显存峰值',
    unit: 'tokens',
    min: 1,
    legacy: { path: 'batch_size' },
  },
  {
    key: 'model.ubatch_size',
    flag: '--ubatch-size',
    short: '-ub',
    type: 'int',
    llamaDefault: 512,
    envName: 'LLAMA_ARG_UBATCH',
    tier: 1,
    group: 'model',
    label: '物理批大小',
    desc: '真正决定单次前向的中间激活显存，需整除逻辑批大小；显存吃紧时优先调它',
    unit: 'tokens',
    min: 1,
  },
  {
    key: 'model.n_predict',
    flag: '--n-predict',
    short: '-n',
    type: 'int',
    llamaDefault: '-1, -1 = infinity',
    envName: 'LLAMA_ARG_N_PREDICT',
    tier: 1,
    group: 'model',
    label: '最大生成长度',
    desc: '服务端单次回复的 token 上限，超过上下文会被截断；-1 表示不限',
    unit: 'tokens',
    min: -1,
    legacy: { path: 'n_predict' },
  },
  {
    key: 'model.keep',
    flag: '--keep',
    type: 'int',
    llamaDefault: '0, -1 = all',
    tier: 1,
    group: 'model',
    label: '常驻前缀长度',
    desc: '强制保留初始 prompt 前 N 个 token 的 KV，配合 prompt cache 保住 system prompt',
    unit: 'tokens',
    min: -1,
  },
  {
    key: 'model.load_mode',
    flag: '--load-mode',
    short: '-lm',
    type: 'enum',
    llamaDefault: 'auto',
    envName: 'LLAMA_ARG_LOAD_MODE',
    tier: 1,
    group: 'model',
    label: '权重加载方式',
    desc: 'mlock 把权重钉在物理内存里避免换出，代价是别的项目抢不到内存；内存不足时才试 mmap',
    options: ['auto', 'none', 'mmap', 'mlock', 'mmap+mlock', 'dio'],
    legacy: { path: 'optional.load_mode', emits: (v) => Boolean(v) && v !== 'auto' },
  },
  {
    key: 'model.lazy_mode',
    flag: '--lazy-mode',
    short: '-lzm',
    type: 'enum',
    llamaDefault: 'auto',
    envName: 'LLAMA_ARG_LAZY_MODE',
    tier: 2,
    group: 'model',
    label: '按需读取张量',
    desc: '逐层 embedding 这类大张量改为按需从磁盘读取，省常驻内存但首次访问更慢；依赖 mmap',
    options: ['auto', 'on', 'off'],
  },
  {
    key: 'model.flash_attn',
    flag: '--flash-attn',
    short: '-fa',
    type: 'enum',
    llamaDefault: 'auto',
    envName: 'LLAMA_ARG_FLASH_ATTN',
    tier: 0,
    group: 'model',
    label: 'Flash Attention',
    desc: '长上下文下明显省显存并提速；量化 KV 时 on 会改变数值精度，不确定就选 auto',
    options: ['on', 'off', 'auto'],
    legacy: { path: 'flash_attn' },
  },
  {
    key: 'model.rope_scaling',
    flag: '--rope-scaling',
    type: 'enum',
    llamaDefault: 'linear unless specified by the model',
    options: ['none', 'linear', 'yarn'],
    envName: 'LLAMA_ARG_ROPE_SCALING_TYPE',
    tier: 1,
    group: 'model',
    label: 'RoPE 缩放方式',
    desc: '模型元数据没写清楚、长上下文出现复读或跑偏时才手动指定缩放方法',
    legacy: { path: 'optional.rope_scaling', emits: (v) => Boolean(v) },
  },
  {
    key: 'model.rope_scale',
    flag: '--rope-scale',
    type: 'float',
    envName: 'LLAMA_ARG_ROPE_SCALE',
    tier: 1,
    group: 'model',
    label: 'RoPE 上下文放大倍数',
    desc: '按 N 倍拉伸位置编码来扩上下文，与 rope-freq-scale 只应设置一个',
    min: 1,
    step: 0.1,
  },
  {
    key: 'model.rope_freq_base',
    flag: '--rope-freq-base',
    type: 'float',
    llamaDefault: 'loaded from model',
    envName: 'LLAMA_ARG_ROPE_FREQ_BASE',
    tier: 1,
    group: 'model',
    label: 'RoPE 基准频率',
    desc: 'NTK-aware 缩放才需要改，填错会让长距离检索整体退化，通常交给模型元数据',
    min: 0,
    legacy: { path: 'optional.rope_freq_base', emits: (v) => Number(v) > 0 },
  },
  {
    key: 'model.rope_freq_scale',
    flag: '--rope-freq-scale',
    type: 'float',
    envName: 'LLAMA_ARG_ROPE_FREQ_SCALE',
    tier: 1,
    group: 'model',
    label: 'RoPE 频率缩放因子',
    desc: '按 1/N 压缩频率来扩展上下文，与 rope-scaling 配套使用',
    min: 0,
    precision: 4,
    legacy: { path: 'optional.rope_freq_scale', emits: (v) => Number(v) > 0 },
  },
  {
    key: 'model.yarn_orig_ctx',
    flag: '--yarn-orig-ctx',
    type: 'int',
    llamaDefault: '0 = model training context size',
    envName: 'LLAMA_ARG_YARN_ORIG_CTX',
    tier: 1,
    group: 'model',
    label: 'YaRN 原始上下文',
    desc: '模型训练时的上下文长度，探测不到时手工填写，填错会让缩放比例失真',
    unit: 'tokens',
    min: 0,
    requires: [{ key: 'model.rope_scaling', oneOf: YARN_SCALING }],
  },
  {
    key: 'model.yarn_ext_factor',
    flag: '--yarn-ext-factor',
    type: 'float',
    llamaDefault: '-1.00, 0.0 = full interpolation',
    envName: 'LLAMA_ARG_YARN_EXT_FACTOR',
    tier: 1,
    group: 'model',
    label: 'YaRN 外推混合因子',
    desc: '控制外推与线性插值的混合比例，-1 表示跟随模型设置',
    min: -1,
    step: 0.1,
    precision: 2,
    requires: [{ key: 'model.rope_scaling', oneOf: YARN_SCALING }],
  },
  {
    key: 'model.yarn_attn_factor',
    flag: '--yarn-attn-factor',
    type: 'float',
    llamaDefault: '-1.00',
    envName: 'LLAMA_ARG_YARN_ATTN_FACTOR',
    tier: 1,
    group: 'model',
    label: 'YaRN 注意力幅度',
    desc: '缩放 sqrt(t) 或注意力幅度，长上下文出现注意力弥散时才调',
    min: -1,
    step: 0.1,
    precision: 2,
    requires: [{ key: 'model.rope_scaling', oneOf: YARN_SCALING }],
  },
  {
    key: 'model.yarn_beta_slow',
    flag: '--yarn-beta-slow',
    type: 'float',
    llamaDefault: '-1.00',
    envName: 'LLAMA_ARG_YARN_BETA_SLOW',
    tier: 1,
    group: 'model',
    label: 'YaRN 高频修正维（alpha）',
    desc: '低维分量的修正区间下界，只在量化感知微调过的模型上有收益',
    min: -1,
    step: 0.1,
    precision: 2,
    requires: [{ key: 'model.rope_scaling', oneOf: YARN_SCALING }],
  },
  {
    key: 'model.yarn_beta_fast',
    flag: '--yarn-beta-fast',
    type: 'float',
    llamaDefault: '-1.00',
    envName: 'LLAMA_ARG_YARN_BETA_FAST',
    tier: 1,
    group: 'model',
    label: 'YaRN 低频修正维（beta）',
    desc: '高分量的修正区间上界，需与 beta-slow 成套调整',
    min: -1,
    step: 0.1,
    precision: 2,
    requires: [{ key: 'model.rope_scaling', oneOf: YARN_SCALING }],
  },
  {
    key: 'model.chat_template',
    flag: '--chat-template',
    type: 'string',
    llamaDefault: 'template taken from model metadata',
    envName: 'LLAMA_ARG_CHAT_TEMPLATE',
    tier: 2,
    group: 'model',
    label: '对话模板覆写',
    desc: '内联 jinja 模板覆盖模型自带模板；填错会让模型输出错乱的角色标记，建议改用模板文件',
  },
  {
    key: 'model.chat_template_file',
    flag: '--chat-template-file',
    type: 'path',
    llamaDefault: 'template taken from model metadata',
    tier: 2,
    group: 'model',
    label: '对话模板文件',
    desc: '从文件读取 jinja 模板，比内联更好维护；同样只在模型模板明显不对时使用',
  },
  {
    key: 'model.jinja',
    flag: '--jinja',
    negFlag: '--no-jinja',
    type: 'bool',
    llamaDefault: 'enabled',
    envName: 'LLAMA_ARG_JINJA',
    tier: 1,
    group: 'model',
    label: 'Jinja 模板引擎',
    desc: '关掉后退回内置的非 jinja 解析，仅用于绕过有问题的模板；同时决定 --chat-template 能否被接受',
    legacy: { path: 'optional.jinja' },
  },
  {
    key: 'model.special',
    flag: '--special',
    short: '-sp',
    type: 'bool',
    llamaDefault: false,
    tier: 2,
    group: 'model',
    label: '输出特殊 token',
    desc: '把结束符等控制 token 一并回传给客户端，仅补全/解析原始输出时开启，正常聊天会看到脏字符',
  },
  {
    key: 'model.spm_infill',
    flag: '--spm-infill',
    type: 'bool',
    llamaDefault: 'disabled',
    tier: 2,
    group: 'model',
    label: 'Infill 采用 SPM 模式',
    desc: '代码补全改用 Suffix/Prefix/Middle 拼接，仅模型明确偏好该顺序时开启',
  },
] as const satisfies readonly ParamDef<ConfigKey>[];
