// =============================================================================
// 参数组：多模态 — 视觉投影器（mmproj）的加载与图像/视频输入的规模控制
//   本文件是这些参数的唯一声明处：命令行、校验、UI、默认值、v1 迁移都由它推导
//   整组只对视觉/多模态模型有意义，纯文本模型全部保持 inherit 即可
// =============================================================================

import type { ParamDef } from '../schema';
import type { ConfigKey } from '../../types';

export const PARAMS_MULTIMODAL = [
  {
    key: 'multimodal.mmproj',
    flag: '--mmproj',
    short: '-mm',
    type: 'path',
    envName: 'LLAMA_ARG_MMPROJ',
    tier: 0,
    group: 'multimodal',
    label: '投影器文件',
    desc: '视觉模型必需的 mmproj 投影器路径，非视觉模型无需设置；用 --hf-repo 拉取自带投影器的仓库时可以留空',
  },
  {
    key: 'multimodal.mmproj_url',
    flag: '--mmproj-url',
    short: '-mmu',
    type: 'string',
    envName: 'LLAMA_ARG_MMPROJ_URL',
    tier: 2,
    group: 'multimodal',
    label: '投影器 URL',
    desc: '直接从远程地址加载投影器，本机没有文件时才用；地址不可达或未走代理会导致启动失败',
  },
  {
    key: 'multimodal.mmproj_auto',
    flag: '--mmproj-auto',
    negFlag: '--no-mmproj-auto',
    type: 'bool',
    llamaDefault: 'enabled',
    envName: 'LLAMA_ARG_MMPROJ_AUTO',
    tier: 1,
    group: 'multimodal',
    label: '自动查找投影器',
    desc: '自动挂上同目录可用的 mmproj，配合 --hf-repo 时最省事；确认是纯文本模型又误放了投影器文件时关掉它，可以省下一份显存',
  },
  {
    key: 'multimodal.mmproj_offload',
    flag: '--mmproj-offload',
    negFlag: '--no-mmproj-offload',
    type: 'bool',
    llamaDefault: 'enabled',
    envName: 'LLAMA_ARG_MMPROJ_OFFLOAD',
    tier: 1,
    group: 'multimodal',
    label: '投影器卸载到 GPU',
    desc: '投影器（视觉编码器）是否在 GPU 上跑，只在显存吃紧时才关；关掉后图像编码会退回 CPU，处理大图会慢一个量级',
  },
  {
    key: 'multimodal.mmproj_device',
    flag: '--mmproj-device',
    short: '-mmdev',
    type: 'string',
    llamaDefault: 'follows --device',
    envName: 'MTMD_BACKEND_DEVICE',
    tier: 2,
    group: 'multimodal',
    label: '投影器设备',
    desc: '单独指定投影器用的设备，多卡时把视觉编码器压到另一张卡给主模型腾显存；填 none 表示完全不卸载，非视觉模型无需设置',
  },
  {
    key: 'multimodal.image_min_tokens',
    flag: '--image-min-tokens',
    type: 'int',
    llamaDefault: 'read from model',
    envName: 'LLAMA_ARG_IMAGE_MIN_TOKENS',
    tier: 2,
    group: 'multimodal',
    label: '单图最小 token 数',
    desc: '只有支持动态分辨率的视觉模型才生效：抬高小图也会占到更多 token，prompt 变长、显存和耗时同步上升',
    min: 1,
    unit: 'tokens',
  },
  {
    key: 'multimodal.image_max_tokens',
    flag: '--image-max-tokens',
    type: 'int',
    llamaDefault: 'read from model',
    envName: 'LLAMA_ARG_IMAGE_MAX_TOKENS',
    tier: 1,
    group: 'multimodal',
    label: '单图最大 token 数',
    desc: '动态分辨率下单图的 token 上限：越大越看得清细节，代价是更容易吃满上下文；固定分辨率模型忽略此项',
    min: 1,
    unit: 'tokens',
  },
  {
    key: 'multimodal.mtmd_batch_max_tokens',
    flag: '--mtmd-batch-max-tokens',
    type: 'int',
    llamaDefault: 1024,
    envName: 'LLAMA_ARG_MTMD_BATCH_MAX_TOKENS',
    tier: 2,
    group: 'multimodal',
    label: '图像编码批上限',
    desc: '一次编码多少个 image token，一次喂多张大图时调小可省显存，调大更快但峰值显存更高',
    min: 1,
    unit: 'tokens',
  },
  {
    key: 'multimodal.video_fps',
    flag: '--video-fps',
    type: 'float',
    llamaDefault: '4.0',
    envName: 'LLAMA_ARG_VIDEO_FPS',
    tier: 2,
    group: 'multimodal',
    label: '视频抽帧率',
    desc: '按此帧率从视频里抽帧，只影响视频输入：调高看得更细但 token 与耗时线性上涨，低帧率素材反而会被插出重复帧',
    min: 0.1,
    precision: 1,
    unit: '帧/秒',
  },
  {
    key: 'multimodal.video_timestamp_interval',
    flag: '--video-timestamp-interval',
    type: 'int',
    llamaDefault: 5000,
    envName: 'LLAMA_ARG_VIDEO_TIMESTAMP_INTERVAL',
    tier: 2,
    group: 'multimodal',
    label: '视频时间戳间隔',
    desc: '每隔多久给视频帧插一条文本时间戳，间隔越小模型越能定位具体时刻，但 prompt 更长、也更容易把注意力从画面本身带走',
    min: 0,
    unit: '毫秒',
  },
  {
    key: 'multimodal.video_ffmpeg_dir',
    flag: '--video-ffmpeg-dir',
    type: 'path',
    pathKind: 'dir',
    llamaDefault: 'search in PATH',
    envName: 'LLAMA_ARG_VIDEO_FFMPEG_DIR',
    tier: 2,
    group: 'multimodal',
    label: 'ffmpeg 目录',
    desc: '指定放着 ffmpeg 与 ffprobe 的目录，PATH 里找不到这两个可执行文件时才需要填；目录里没有会导致视频输入直接失败',
  },
] as const satisfies readonly ParamDef<ConfigKey>[];
