// =============================================================================
// 参数组：采样 — 生成随机性、重复惩罚、DRY/Mirostat/adaptive-p 与结构化输出
//   本文件是这些参数的唯一声明处：命令行、校验、UI、默认值、v1 迁移都由它推导
//   全部默认 inherit：旧版硬编码的 20/0.4/1.1 与 llama.cpp 真实默认值的漂移即为 bug
// =============================================================================

import type { ParamDef } from '../schema';
import type { ConfigKey } from '../../types';

export const PARAMS_SAMPLING = [
  {
    key: 'sampling.temperature',
    flag: '--temperature',
    type: 'float',
    llamaDefault: '0.80',
    tier: 0,
    group: 'sampling',
    label: '温度',
    desc: '越大越发散、越小越保守，0 退化为贪心解码；开启 Mirostat 时由 Mirostat 接管',
    min: 0,
    max: 2,
    step: 0.05,
    precision: 2,
    legacy: { path: 'optional.temperature', emits: (v) => Number(v) > 0 && Number(v) !== 0.8 },
  },
  {
    key: 'sampling.top_k',
    flag: '--top-k',
    type: 'int',
    llamaDefault: '40, 0 = disabled',
    envName: 'LLAMA_ARG_TOP_K',
    tier: 0,
    group: 'sampling',
    label: 'Top-K',
    desc: '每步只在概率最高的 k 个 token 中采样，越小越稳；0 表示关闭，大于词表大小等于不起作用',
    min: 0,
    legacy: { path: 'optional.top_k', emits: (v) => Number(v) > 0 && Number(v) !== 40 },
  },
  {
    key: 'sampling.top_p',
    flag: '--top-p',
    type: 'float',
    llamaDefault: '0.95, 1.0 = disabled',
    tier: 0,
    group: 'sampling',
    label: 'Top-P',
    desc: '核采样：在累计概率达 p 的最小候选集内采样，与 Top-K 可同时收紧；1 表示关闭',
    min: 0,
    max: 1,
    step: 0.05,
    precision: 2,
    legacy: { path: 'optional.top_p', emits: (v) => Number(v) > 0 && Number(v) !== 0.95 },
  },
  {
    key: 'sampling.min_p',
    flag: '--min-p',
    type: 'float',
    llamaDefault: '0.05, 0.0 = disabled',
    tier: 0,
    group: 'sampling',
    label: 'Min-P',
    desc: '按最高概率的比例裁掉长尾，候选数随分布自适应，低质量模型上比固定 Top-K 更稳；0 表示关闭',
    min: 0,
    max: 1,
    step: 0.01,
    precision: 2,
    legacy: { path: 'optional.min_p', emits: (v) => Number(v) > 0 },
  },
  {
    key: 'sampling.top_n_sigma',
    flag: '--top-nsigma',
    type: 'float',
    llamaDefault: '-1.00, -1.0 = disabled',
    tier: 1,
    group: 'sampling',
    label: 'Top-N-Sigma',
    desc: '按 logits 标准差做 n-sigma 截断，对分布尖锐度比 Top-K 更鲁棒；-1 表示关闭',
    min: -1,
    max: 10,
    step: 0.1,
    precision: 2,
  },
  {
    key: 'sampling.typical_p',
    flag: '--typical-p',
    type: 'float',
    llamaDefault: '1.00, 1.0 = disabled',
    tier: 1,
    group: 'sampling',
    label: 'Typical-P',
    desc: '局部典型采样：剔除信息量偏离典型的 token，对微调后概率失真的模型效果好；1 表示关闭，开启 Mirostat 时失效',
    min: 0,
    max: 1,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'sampling.xtc_probability',
    flag: '--xtc-probability',
    type: 'float',
    llamaDefault: '0.00, 0.0 = disabled',
    tier: 1,
    group: 'sampling',
    label: 'XTC 概率',
    desc: '有该概率剔除「概率第二高」的 token，用来打掉了套路化接续；0 表示关闭，会明显降低多样性',
    min: 0,
    max: 1,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'sampling.xtc_threshold',
    flag: '--xtc-threshold',
    type: 'float',
    llamaDefault: '0.10, 1.0 = disabled',
    tier: 1,
    group: 'sampling',
    label: 'XTC 阈值',
    desc: '只有概率高于该值的候选才参与 XTC 剔除，避免误伤低概率好词；1 表示关闭',
    min: 0,
    max: 1,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'sampling.dynatemp_range',
    flag: '--dynatemp-range',
    type: 'float',
    llamaDefault: '0.00, 0.0 = disabled',
    tier: 1,
    group: 'sampling',
    label: '动态温度范围',
    desc: '按当前 logits 的熵在 temp±range 内动态调温，创作类长文更起伏；0 表示关闭',
    min: 0,
    max: 1,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'sampling.dynatemp_exponent',
    flag: '--dynatemp-exp',
    type: 'float',
    llamaDefault: '1.00',
    tier: 1,
    group: 'sampling',
    label: '动态温度指数',
    desc: '动态温度对熵的响应指数，>1 更激进；仅在动态温度范围非 0 时有意义',
    min: 0,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'sampling.mirostat',
    flag: '--mirostat',
    type: 'int',
    llamaDefault: '0, 0 = disabled, 1 = Mirostat, 2 = Mirostat 2.0',
    tier: 1,
    group: 'sampling',
    label: 'Mirostat',
    desc: '按目标困惑度自适应采样：1 = Mirostat，2 = Mirostat 2.0（更稳）。开启后 Top-K、Top-P、Typical-P 全部被忽略',
    min: 0,
    max: 2,
  },
  {
    key: 'sampling.mirostat_lr',
    flag: '--mirostat-lr',
    type: 'float',
    llamaDefault: '0.10',
    tier: 1,
    group: 'sampling',
    label: 'Mirostat 学习率',
    desc: '参数 eta：越大越快逼近目标困惑度，过大会剧烈抖动甚至乱码；仅在 Mirostat 开启时生效',
    min: 0,
    step: 0.01,
    precision: 2,
    requires: [{ key: 'sampling.mirostat', oneOf: [1, 2] }],
  },
  {
    key: 'sampling.mirostat_ent',
    flag: '--mirostat-ent',
    type: 'float',
    llamaDefault: '5.00',
    tier: 1,
    group: 'sampling',
    label: 'Mirostat 目标熵',
    desc: '参数 tau：期望困惑度（约 ln(k)），越大越发散；仅在 Mirostat 开启时生效',
    min: 0,
    step: 0.1,
    precision: 2,
    requires: [{ key: 'sampling.mirostat', oneOf: [1, 2] }],
  },
  {
    key: 'sampling.adaptive_target',
    flag: '--adaptive-target',
    type: 'float',
    llamaDefault: '-1.00',
    tier: 1,
    group: 'sampling',
    label: 'Adaptive-P 目标',
    desc: 'adaptive-p：向该目标概率靠拢地挑选 token，负数表示关闭',
    min: -1,
    max: 1,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'sampling.adaptive_decay',
    flag: '--adaptive-decay',
    type: 'float',
    llamaDefault: '0.90',
    tier: 1,
    group: 'sampling',
    label: 'Adaptive-P 衰减',
    desc: 'adaptive-p 的衰减率，越大越保守；仅在目标概率有效时参与计算',
    min: 0,
    max: 0.99,
    step: 0.01,
    precision: 2,
  },
  {
    key: 'sampling.repeat_penalty',
    flag: '--repeat-penalty',
    type: 'float',
    llamaDefault: '1.00, 1.0 = disabled',
    tier: 0,
    group: 'sampling',
    label: '重复惩罚',
    desc: '对重复序列的乘性惩罚，>1 抑制复读；超过 1.3 容易出现措辞漂移和乱码；1 表示关闭',
    min: 0,
    max: 3,
    step: 0.05,
    precision: 2,
    legacy: { path: 'optional.repeat_penalty', emits: (v) => Number(v) > 0 && Number(v) !== 1 },
  },
  {
    key: 'sampling.repeat_last_n',
    flag: '--repeat-last-n',
    type: 'int',
    llamaDefault: '64, 0 = disabled',
    tier: 1,
    group: 'sampling',
    label: '重复惩罚窗口',
    desc: '重复惩罚只回看最近 n 个 token，窗口越小越宽松；0 表示关闭该惩罚',
    min: 0,
    unit: 'tokens',
    legacy: { path: 'optional.repeat_last_n', emits: (v) => Number(v) > 0 && Number(v) !== 64 },
  },
  {
    key: 'sampling.presence_penalty',
    flag: '--presence-penalty',
    type: 'float',
    llamaDefault: '0.00, 0.0 = disabled',
    tier: 1,
    group: 'sampling',
    label: '存在惩罚',
    desc: '只要出现过就固定扣一次分，鼓励换新词；与重复惩罚叠加容易过度发散',
    min: -2,
    max: 2,
    step: 0.1,
    precision: 2,
    legacy: { path: 'optional.presence_penalty', emits: (v) => Number(v) > 0 },
  },
  {
    key: 'sampling.frequency_penalty',
    flag: '--frequency-penalty',
    type: 'float',
    llamaDefault: '0.00, 0.0 = disabled',
    tier: 1,
    group: 'sampling',
    label: '频率惩罚',
    desc: '按出现次数线性扣分，专治口头禅与循环；长文本下过强会把内容写成碎片',
    min: -2,
    max: 2,
    step: 0.1,
    precision: 2,
    legacy: { path: 'optional.frequency_penalty', emits: (v) => Number(v) > 0 },
  },
  {
    key: 'sampling.dry_multiplier',
    flag: '--dry-multiplier',
    type: 'float',
    llamaDefault: '0.00, 0.0 = disabled',
    tier: 1,
    group: 'sampling',
    label: 'DRY 强度',
    desc: 'DRY 重复惩罚系数，对长上下文的整段复读特别有效；0 表示关闭 DRY',
    min: 0,
    max: 2,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'sampling.dry_base',
    flag: '--dry-base',
    type: 'float',
    llamaDefault: '1.75',
    tier: 1,
    group: 'sampling',
    label: 'DRY 底数',
    desc: 'DRY 的指数底数：重复片段越长罚得越重，配合允许长度使用',
    min: 0,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'sampling.dry_allowed_length',
    flag: '--dry-allowed-length',
    type: 'int',
    llamaDefault: '2',
    tier: 1,
    group: 'sampling',
    label: 'DRY 允许重复长度',
    desc: '不超过该长度的重复子串不惩罚，调到 1 会开始罚短语',
    min: 0,
    unit: 'tokens',
  },
  {
    key: 'sampling.dry_penalty_last_n',
    flag: '--dry-penalty-last-n',
    type: 'int',
    llamaDefault: '64, 0 = disable',
    tier: 1,
    group: 'sampling',
    label: 'DRY 回看窗口',
    desc: 'DRY 惩罚回看的窗口长度；0 表示关闭窗口限制、回看整个上下文',
    min: 0,
    unit: 'tokens',
  },
  {
    key: 'sampling.dry_sequence_breaker',
    flag: '--dry-sequence-breaker',
    emit: 'repeat',
    type: 'string[]',
    tier: 1,
    group: 'sampling',
    label: 'DRY 断点符',
    desc: '追加重复切断符；一旦设置就会清空内置的换行、冒号、双引号、星号四个默认断点，填 none 表示不使用任何断点',
  },
  {
    key: 'sampling.samplers',
    flag: '--samplers',
    type: 'string',
    llamaDefault: 'penalties;dry;top_n_sigma;top_k;typ_p;top_p;min_p;xtc;temperature',
    tier: 1,
    group: 'sampling',
    label: '采样器顺序',
    desc: '分号分隔的采样器执行链，删掉某项即跳过该采样器；可用于化解 Mirostat 与 Top-K/Top-P 的互斥，顺序错了结果完全不同',
  },
  {
    key: 'sampling.seed',
    flag: '--seed',
    short: '-s',
    type: 'int',
    llamaDefault: '-1, use random seed for -1',
    tier: 0,
    group: 'sampling',
    label: '随机种子',
    desc: '固定种子才能复现输出，-1 为随机；并发槽位数大于 1 时无法严格复现',
    min: -1,
  },
  {
    key: 'sampling.ignore_eos',
    flag: '--ignore-eos',
    type: 'bool',
    tier: 1,
    group: 'sampling',
    label: '忽略结束符',
    desc: '无视 EOS 一直生成到长度上限，只用于跑吞吐压测；聊天场景会把上下文写满',
  },
  {
    key: 'sampling.logit_bias',
    flag: '--logit-bias',
    short: '-l',
    emit: 'repeat',
    type: 'string[]',
    tier: 1,
    group: 'sampling',
    label: 'Logit 偏置',
    desc: '按 token id 改写 logits，形如 15043+1 加分、15043+-100 禁用，可重复传多条；id 需先用 /tokenize 取得',
  },
  {
    key: 'sampling.grammar',
    flag: '--grammar',
    type: 'string',
    tier: 2,
    group: 'sampling',
    label: 'BNF 语法',
    desc: '用类 BNF 语法硬约束输出格式；写坏的语法会让生成明显变慢甚至卡死',
  },
  {
    key: 'sampling.grammar_file',
    flag: '--grammar-file',
    type: 'path',
    tier: 2,
    group: 'sampling',
    label: '语法文件',
    desc: '从文件读取 BNF 语法，长语法用它免得踩命令行转义',
  },
  {
    key: 'sampling.json_schema',
    flag: '--json-schema',
    short: '-j',
    type: 'string',
    widget: 'json',
    tier: 2,
    group: 'sampling',
    label: 'JSON Schema',
    desc: '直接给 JSON Schema 让输出必然合法，比手写 grammar 省事；会盖过采样设置，非结构化任务不要开',
  },
  {
    key: 'sampling.json_schema_file',
    flag: '--json-schema-file',
    short: '-jf',
    type: 'path',
    tier: 2,
    group: 'sampling',
    label: 'JSON Schema 文件',
    desc: '从文件读取 JSON Schema，便于与 tool 定义共用同一份 schema',
  },
] as const satisfies readonly ParamDef<ConfigKey>[];
