// =============================================================================
// 参数组：服务与网络 — llama-server 的监听、端点、模型路由与并发槽位
//   本文件是这些参数的唯一声明处：命令行、校验、UI、默认值、v1 迁移都由它推导
// =============================================================================

import type { ParamDef } from '../schema';
import type { ConfigKey } from '../../types';

export const PARAMS_SERVER = [
  {
    key: 'server.host',
    flag: '--host',
    type: 'string',
    llamaDefault: '127.0.0.1',
    tier: 0,
    group: 'server',
    label: '监听地址',
    desc: '0.0.0.0 表示允许局域网访问；仅本机使用建议保持 127.0.0.1',
    default: '127.0.0.1',
    legacy: { path: 'host' },
  },
  {
    key: 'server.port',
    flag: '--port',
    type: 'int',
    llamaDefault: 8080,
    tier: 0,
    group: 'server',
    label: '端口',
    desc: '本机已有服务占用该端口时会启动失败；只监听本机时保持 8080 即可',
    min: 1,
    max: 65535,
    default: 8080,
    legacy: { path: 'port' },
  },
  {
    key: 'server.timeout',
    flag: '--timeout',
    short: '-to',
    type: 'int',
    llamaDefault: 3600,
    tier: 0,
    group: 'server',
    label: '读写超时',
    desc: '单个请求的读/写超时秒数，长上下文首 token 慢时适当调大',
    unit: '秒',
    min: 1,
    default: 3600,
    legacy: { path: 'timeout' },
  },
  {
    key: 'server.api_key',
    flag: '--api-key',
    type: 'secret',
    llamaDefault: 'none',
    tier: 0,
    group: 'server',
    label: 'API Key',
    desc: '多个用逗号分隔；监听 0.0.0.0 时强烈建议设置。界面上永远脱敏显示',
    legacy: { path: 'api_key', emits: (v) => Boolean(v) },
  },
  {
    key: 'server.api_key_file',
    flag: '--api-key-file',
    type: 'secret',
    llamaDefault: 'none',
    tier: 2,
    group: 'server',
    label: 'API Key 文件',
    desc: '每行一个 key，# 开头为注释，避免把密钥写进配置',
  },
  {
    key: 'server.reuse_port',
    flag: '--reuse-port',
    type: 'bool',
    llamaDefault: 'disabled',
    tier: 2,
    group: 'server',
    label: '复用端口',
    desc: '允许多个 socket 绑定同一端口，排障时慎用',
  },
  {
    key: 'server.api_prefix',
    flag: '--api-prefix',
    type: 'string',
    tier: 2,
    group: 'server',
    label: 'API 前缀',
    desc: '反向代理下给服务加路径前缀，不带结尾斜杠',
  },
  {
    key: 'server.static_path',
    flag: '--path',
    type: 'path',
    pathKind: 'dir',
    tier: 2,
    group: 'server',
    label: '静态目录',
    desc: '从此目录提供静态文件',
  },
  {
    key: 'server.media_path',
    flag: '--media-path',
    type: 'path',
    pathKind: 'dir',
    llamaDefault: 'disabled',
    tier: 2,
    group: 'server',
    label: '媒体目录',
    desc: '允许通过 file:// 相对路径读取的本地媒体根目录',
  },
  {
    key: 'server.cors_origins',
    flag: '--cors-origins',
    type: 'string',
    llamaDefault: '*',
    tier: 1,
    group: 'server',
    label: 'CORS 来源',
    desc: '逗号分隔；填 localhost 表示只放行本机来源',
  },
  {
    key: 'server.metrics',
    flag: '--metrics',
    type: 'bool',
    llamaDefault: 'disabled',
    tier: 1,
    group: 'server',
    label: 'Prometheus 指标端点',
    desc: '暴露 /metrics 供监控系统抓取，本机自用没有意义，关掉省一个公开入口',
    legacy: { path: 'metrics', emits: (v) => v === true },
  },
  {
    key: 'server.props',
    flag: '--props',
    type: 'bool',
    llamaDefault: 'disabled',
    tier: 2,
    group: 'server',
    label: '开放 /props',
    desc: '允许通过 POST /props 修改全局属性，公网环境不要开',
  },
  {
    key: 'server.slots',
    flag: '--slots',
    negFlag: '--no-slots',
    type: 'bool',
    llamaDefault: 'enabled',
    tier: 1,
    group: 'server',
    label: '槽位监控端点',
    desc: '/slots 查看每个并发槽的实时状态',
  },
  {
    key: 'server.slot_save_path',
    flag: '--slot-save-path',
    type: 'path',
    pathKind: 'dir',
    llamaDefault: 'disabled',
    tier: 2,
    group: 'server',
    label: '槽位 KV 存档目录',
    desc: '把每个并发槽的 KV 状态存档到该目录，重启后可恢复长对话的缓存；目录会随使用不断变大',
  },
  {
    key: 'server.slot_prompt_similarity',
    flag: '--slot-prompt-similarity',
    short: '-sps',
    type: 'float',
    llamaDefault: '0.10',
    tier: 2,
    group: 'server',
    label: '槽位提示词相似度',
    desc: '相似度足够高时复用槽位缓存，0 表示关闭',
    min: 0,
    max: 1,
    step: 0.05,
    precision: 2,
  },
  {
    key: 'server.models_dir',
    flag: '--models-dir',
    type: 'path',
    pathKind: 'dir',
    llamaDefault: 'disabled',
    tier: 0,
    group: 'server',
    label: '模型目录',
    desc: 'router 模式扫描 GGUF 的目录，也是本启动器下载/选择模型的默认目录；与 model.model 至少要设置一个',
    legacy: { path: 'models_dir', emits: (v) => Boolean(v) },
  },
  {
    key: 'server.models_max',
    flag: '--models-max',
    type: 'int',
    llamaDefault: 4,
    tier: 1,
    group: 'server',
    label: '同时加载模型数',
    desc: '0 = 不限制，超出后按 LRU 卸载',
    min: 0,
    default: 2,
    legacy: { path: 'models_max' },
  },
  {
    key: 'server.models_autoload',
    flag: '--models-autoload',
    negFlag: '--no-models-autoload',
    type: 'bool',
    llamaDefault: 'enabled',
    tier: 2,
    group: 'server',
    label: '启动即加载模型',
    desc: '启动时就把模型目录里的 GGUF 读进显存，第一个请求不用等加载；同时放多个大模型时关掉它，改成按需加载',
  },
  {
    key: 'server.alias',
    flag: '--alias',
    short: '-a',
    type: 'string',
    tier: 2,
    group: 'server',
    label: '模型别名',
    desc: 'API 中暴露的名字，逗号分隔，避免把文件路径泄露给客户端',
  },
  {
    key: 'server.tags',
    flag: '--tags',
    type: 'string',
    tier: 2,
    group: 'server',
    label: '模型标签',
    desc: '仅用于展示，不参与路由',
  },
  {
    key: 'server.parallel',
    flag: '--parallel',
    short: '-np',
    type: 'int',
    llamaDefault: '-1 = auto',
    tier: 0,
    group: 'server',
    label: '并发槽位数',
    desc: '每个槽位独立处理一路请求，KV cache 按槽位共享或切分',
    min: -1,
    legacy: { path: 'parallel' },
  },
  {
    key: 'server.cont_batching',
    flag: '--cont-batching',
    short: '-cb',
    negFlag: '--no-cont-batching',
    type: 'bool',
    llamaDefault: 'enabled',
    tier: 1,
    group: 'server',
    label: '连续批处理',
    desc: '把多个请求的 prompt 拼批处理，并发场景几乎总是更快',
    legacy: { path: 'optional.cont_batching' },
  },
  {
    key: 'server.warmup',
    flag: '--warmup',
    negFlag: '--no-warmup',
    type: 'bool',
    llamaDefault: 'enabled',
    tier: 2,
    group: 'server',
    label: '启动预热',
    desc: '用空请求预热计算图，关掉可略微加快启动',
  },
  {
    key: 'server.sleep_idle_seconds',
    flag: '--sleep-idle-seconds',
    type: 'int',
    llamaDefault: '-1 = disabled',
    tier: 1,
    group: 'server',
    label: '空闲休眠',
    desc: '空闲若干秒后释放显存，下次请求自动唤醒；与常驻显存模型互斥使用',
    unit: '秒',
    min: -1,
  },
  {
    key: 'server.embedding',
    flag: '--embedding',
    type: 'bool',
    llamaDefault: 'disabled',
    tier: 1,
    group: 'server',
    label: '向量模式',
    desc: '只服务 embedding 请求，需模型本身支持；此模式下聊天接口不可用',
    legacy: { path: 'optional.embedding', emits: (v) => v === true },
  },
  {
    key: 'server.rerank',
    flag: '--rerank',
    type: 'bool',
    llamaDefault: 'disabled',
    tier: 2,
    group: 'server',
    label: '重排端点',
    desc: '开启 /rerank 接口，仅专用 rerank 模型需要',
  },
  {
    key: 'server.pooling',
    flag: '--pooling',
    type: 'enum',
    llamaDefault: 'model default',
    tier: 2,
    group: 'server',
    label: '池化方式',
    desc: '向量模式的句向量聚合方式，留空跟随模型元数据',
    options: ['none', 'mean', 'cls', 'last', 'rank'],
    legacy: { path: 'optional.pooling', emits: (v) => Boolean(v) && v !== 'none' },
  },
  {
    key: 'server.embd_normalize',
    flag: '--embd-normalize',
    type: 'int',
    llamaDefault: 2,
    tier: 2,
    group: 'server',
    label: '向量归一化',
    desc: '-1 不归一化，0 最大 int16，1 曼哈顿，2 欧氏，>2 为 p 范数',
    min: -1,
  },
  {
    key: 'server.webui',
    flag: '--ui',
    negFlag: '--no-ui',
    type: 'bool',
    llamaDefault: 'enabled',
    tier: 1,
    group: 'server',
    label: '内置 Web 界面',
    desc: '关掉后只提供 API，不暴露内置聊天页面',
  },
] as const satisfies readonly ParamDef<ConfigKey>[];
