// =============================================================================
// 参数组：投机解码 — --spec-type 分支、草稿模型与 n-gram / lookup 缓存调优
//   本文件是这些参数的唯一声明处：命令行、校验、UI、默认值、v1 迁移都由它推导
//   draft-* 需要草稿模型文件（draft-mtp 用主模型自带 MTP 头，例外）；ngram-* 不需要，且不支持 --spec-draft-n-max
// =============================================================================

import type { ParamDef } from '../schema';
import type { ConfigKey } from '../../types';

/** 需要草稿模型文件的类型（draft-mtp 用主模型自带的 MTP 头，不需要额外文件） */
const NEEDS_DRAFT_MODEL = ['draft-simple', 'draft-eagle3', 'draft-dflash', 'draft-dspark'];

/** 全部 draft-* 类型：它们共享 --spec-draft-* 调优参数，ngram-* 则完全不认这些参数 */
const DRAFT_TYPES = [...NEEDS_DRAFT_MODEL, 'draft-mtp'];

export const PARAMS_SPECULATIVE = [
  {
    key: 'speculative.spec_type',
    flag: '--spec-type',
    type: 'enum',
    llamaDefault: 'none',
    tier: 0,
    group: 'speculative',
    label: '投机解码方式',
    desc: '先草拟多个 token 再让主模型一次验证来加速。draft-* 需额外草稿模型（draft-mtp 用主模型自带 MTP 头，不需要）；ngram-* 全部不需要草稿模型，但改用各自的尺寸参数',
    options: ['none', ...DRAFT_TYPES, 'ngram-cache', 'ngram-simple', 'ngram-map-k', 'ngram-map-k4v', 'ngram-mod'],
    legacy: { path: 'spec_type', emits: (v) => Boolean(v) && v !== 'none' },
  },
  {
    key: 'speculative.draft_n_max',
    flag: '--spec-draft-n-max',
    type: 'int',
    llamaDefault: '3',
    envName: 'LLAMA_ARG_SPEC_DRAFT_N_MAX',
    tier: 0,
    group: 'speculative',
    label: '草拟 token 数',
    desc: '每轮最多草拟并交由主模型验证的 token 数；越大潜在加速越高，但命中率下降后反而变慢。ngram-* 不支持此参数',
    min: 1,
    unit: 'tokens',
    requires: [
      { key: 'speculative.spec_type', oneOf: DRAFT_TYPES },
    ],
    legacy: { path: 'mtp', emits: (v) => Number(v) > 0 },
  },
  {
    key: 'speculative.draft_n_min',
    flag: '--spec-draft-n-min',
    type: 'int',
    llamaDefault: '0',
    envName: 'LLAMA_ARG_SPEC_DRAFT_N_MIN',
    tier: 2,
    group: 'speculative',
    label: '最少草拟 token 数',
    desc: '低于该数量的草稿不启用，0 表示贪心式逐 token 草拟；只在草稿模型类方式下有意义',
    min: 0,
    unit: 'tokens',
    requires: [
      { key: 'speculative.spec_type', oneOf: DRAFT_TYPES },
    ],
  },
  {
    key: 'speculative.draft_model',
    flag: '--spec-draft-model',
    type: 'path',
    llamaDefault: 'unused',
    tier: 1,
    group: 'speculative',
    label: '草稿模型',
    desc: '草稿用的 GGUF，必须与主模型同分词器，等价旧写法 --model-draft；不填则草稿不生效',
    requiredWhen: {
      rule: { key: 'speculative.spec_type', oneOf: NEEDS_DRAFT_MODEL },
      message: '该投机解码方式需要选择草稿模型文件',
    },
    requires: [
      { key: 'speculative.spec_type', oneOf: NEEDS_DRAFT_MODEL },
    ],
    legacy: { path: 'spec_draft_model', emits: (v) => Boolean(v) },
  },
  {
    key: 'speculative.draft_ngl',
    flag: '--spec-draft-ngl',
    type: 'string',
    llamaDefault: 'auto',
    tier: 1,
    group: 'speculative',
    label: '草稿模型卸载层数',
    desc: '接受数字、auto 或 all，等价 --n-gpu-layers-draft；显存吃紧时调小，草稿放 CPU 会拖慢加速比',
    requires: [
      { key: 'speculative.spec_type', oneOf: NEEDS_DRAFT_MODEL },
    ],
    legacy: { path: 'spec_draft_ngl', emits: (v) => Boolean(v) && v !== 'auto' },
  },
  {
    key: 'speculative.draft_type_k',
    flag: '--spec-draft-type-k',
    type: 'enum',
    llamaDefault: 'f16',
    tier: 2,
    group: 'speculative',
    label: '草稿 K cache 类型',
    desc: '草稿模型的 K cache 量化，等价 --cache-type-k-draft；省显存但可能降低草稿命中率',
    options: ['f32', 'f16', 'bf16', 'q8_0', 'q4_0', 'q4_1', 'iq4_nl', 'q5_0', 'q5_1'],
    requires: [
      { key: 'speculative.spec_type', oneOf: DRAFT_TYPES },
    ],
  },
  {
    key: 'speculative.draft_type_v',
    flag: '--spec-draft-type-v',
    type: 'enum',
    llamaDefault: 'f16',
    tier: 2,
    group: 'speculative',
    label: '草稿 V cache 类型',
    desc: '草稿模型的 V cache 量化，等价 --cache-type-v-draft；V 压得越狠对精度影响越大',
    options: ['f32', 'f16', 'bf16', 'q8_0', 'q4_0', 'q4_1', 'iq4_nl', 'q5_0', 'q5_1'],
    requires: [
      { key: 'speculative.spec_type', oneOf: DRAFT_TYPES },
    ],
  },
  {
    key: 'speculative.draft_p_split',
    flag: '--spec-draft-p-split',
    type: 'float',
    llamaDefault: '0.10',
    tier: 2,
    group: 'speculative',
    label: '草稿概率切分阈值',
    desc: '草稿 token 概率低于该值时提前截断草稿，减少注定被拒的验证开销；调太小等于不截断',
    min: 0,
    max: 1,
    step: 0.05,
    precision: 2,
    requires: [
      { key: 'speculative.spec_type', oneOf: DRAFT_TYPES },
    ],
  },
  {
    key: 'speculative.draft_p_min',
    flag: '--spec-draft-p-min',
    type: 'float',
    llamaDefault: '0.00',
    envName: 'LLAMA_ARG_SPEC_DRAFT_P_MIN',
    tier: 2,
    group: 'speculative',
    label: '草稿最小接受概率',
    desc: '贪心截断阈值：草稿概率低于该值即停止接受后续草稿，命中率低时调高能止损',
    min: 0,
    max: 1,
    step: 0.05,
    precision: 2,
    requires: [
      { key: 'speculative.spec_type', oneOf: DRAFT_TYPES },
    ],
  },
  {
    key: 'speculative.draft_backend_sampling',
    flag: '--spec-draft-backend-sampling',
    negFlag: '--no-spec-draft-backend-sampling',
    type: 'bool',
    llamaDefault: 'enabled',
    tier: 2,
    group: 'speculative',
    label: '草稿走后端采样',
    desc: '草稿采样交给计算后端执行，通常更快；关掉后 CPU 侧采样更可复现，但草拟变慢',
    requires: [
      { key: 'speculative.spec_type', oneOf: DRAFT_TYPES },
    ],
  },
  {
    key: 'speculative.ngram_mod_n_min',
    flag: '--spec-ngram-mod-n-min',
    type: 'int',
    llamaDefault: '48',
    tier: 1,
    group: 'speculative',
    label: 'ngram-mod 最小长度',
    desc: '参与草稿的最短 n-gram 长度，越大越保守、误草拟越少',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-mod'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_mod_n_max',
    flag: '--spec-ngram-mod-n-max',
    type: 'int',
    llamaDefault: '64',
    tier: 1,
    group: 'speculative',
    label: 'ngram-mod 最大长度',
    desc: '单次草拟的最长 n-gram，决定加速上限；过大时命中率下滑反而变慢',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-mod'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_mod_n_match',
    flag: '--spec-ngram-mod-n-match',
    type: 'int',
    llamaDefault: '24',
    tier: 1,
    group: 'speculative',
    label: 'ngram-mod 查表长度',
    desc: '用最近多少个 token 去历史里匹配，越短越容易命中但也越容易草拟错',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-mod'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_simple_size_n',
    flag: '--spec-ngram-simple-size-n',
    type: 'int',
    llamaDefault: '12',
    tier: 1,
    group: 'speculative',
    label: 'ngram-simple 匹配长度 N',
    desc: '用最近 N 个 token 作为查询串去上下文里找匹配',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-simple'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_simple_size_m',
    flag: '--spec-ngram-simple-size-m',
    type: 'int',
    llamaDefault: '48',
    tier: 1,
    group: 'speculative',
    label: 'ngram-simple 草稿长度 M',
    desc: '命中后最多沿历史往下草拟 M 个 token，是这种方式的加速上限',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-simple'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_simple_min_hits',
    flag: '--spec-ngram-simple-min-hits',
    type: 'int',
    llamaDefault: '1',
    tier: 2,
    group: 'speculative',
    label: 'ngram-simple 最少命中',
    desc: '上下文里至少出现这么多次匹配才草拟，调高能滤掉偶发重合',
    min: 1,
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-simple'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_map_k_size_n',
    flag: '--spec-ngram-map-k-size-n',
    type: 'int',
    llamaDefault: '12',
    tier: 2,
    group: 'speculative',
    label: 'ngram-map-k 匹配长度 N',
    desc: '哈希映射表里每个键的 n-gram 长度',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-map-k'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_map_k_size_m',
    flag: '--spec-ngram-map-k-size-m',
    type: 'int',
    llamaDefault: '48',
    tier: 2,
    group: 'speculative',
    label: 'ngram-map-k 草稿长度 M',
    desc: '命中后最多草拟的 token 数，加速上限',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-map-k'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_map_k_min_hits',
    flag: '--spec-ngram-map-k-min-hits',
    type: 'int',
    llamaDefault: '1',
    tier: 2,
    group: 'speculative',
    label: 'ngram-map-k 最少命中',
    desc: '该键的命中计数门槛，低于此值不出草稿',
    min: 1,
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-map-k'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_map_k4v_size_n',
    flag: '--spec-ngram-map-k4v-size-n',
    type: 'int',
    llamaDefault: '12',
    tier: 2,
    group: 'speculative',
    label: 'ngram-map-k4v 匹配长度 N',
    desc: '每个键最多存 4 个候选值，键的 n-gram 长度即此参数',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-map-k4v'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_map_k4v_size_m',
    flag: '--spec-ngram-map-k4v-size-m',
    type: 'int',
    llamaDefault: '48',
    tier: 2,
    group: 'speculative',
    label: 'ngram-map-k4v 草稿长度 M',
    desc: '命中后最多草拟的 token 数，加速上限',
    min: 1,
    unit: 'tokens',
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-map-k4v'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.ngram_map_k4v_min_hits',
    flag: '--spec-ngram-map-k4v-min-hits',
    type: 'int',
    llamaDefault: '1',
    tier: 2,
    group: 'speculative',
    label: 'ngram-map-k4v 最少命中',
    desc: '该键的命中计数门槛，低于此值不出草稿',
    min: 1,
    requires: [{ key: 'speculative.spec_type', oneOf: ['ngram-map-k4v'] }],
    visibleWhen: (p) => String(p['speculative.spec_type'] ?? '').startsWith('ngram-'),
  },
  {
    key: 'speculative.lookup_cache_static',
    flag: '--lookup-cache-static',
    short: '-lcs',
    type: 'path',
    tier: 2,
    group: 'speculative',
    label: '静态查找缓存',
    desc: '预建的 lookup 缓存路径，只读不被生成更新，适合固定语料（如整仓代码）反复问答',
  },
  {
    key: 'speculative.lookup_cache_dynamic',
    flag: '--lookup-cache-dynamic',
    short: '-lcd',
    type: 'path',
    tier: 2,
    group: 'speculative',
    label: '动态查找缓存',
    desc: '生成过程中持续累积并在退出时写回的缓存路径，越用命中越高；文件会随使用不断变大',
  },
] as const satisfies readonly ParamDef<ConfigKey>[];
